// GlobalEventCodeGenerator.cs（完全修正版）

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using GenBall.Event.Templates;
using UnityEditor;
using UnityEngine;

namespace GenBall.Event.Editor
{
    public static class GlobalEventCodeGenerator
    {
        [MenuItem("Tools/事件/全局事件/生成全局事件系统代码")]
        public static void GenerateGlobalEventCode()
        {
            var events = ValueEventTemplateConfig.Events;
            
            // 收集所有需要的命名空间
            var namespaces = new HashSet<string>
            {
                "System",
                "Yueyn.Event",
                "Yueyn.Base.ReferencePool",
                "GenBall.Event"
            };
            
            foreach (var evt in events)
            {
                if (!string.IsNullOrEmpty(evt.TypeNamespace))
                {
                    namespaces.Add(evt.TypeNamespace);
                }
            }
            
            // 添加Unity常用命名空间
            namespaces.Add("UnityEngine");
            
            StringBuilder sb = new StringBuilder();
            
            // 头部信息
            sb.AppendLine("// ============================================================================");
            sb.AppendLine("// Auto-generated Global Event System - DO NOT EDIT MANUALLY");
            sb.AppendLine("// Generated by: GlobalEventCodeGenerator.cs");
            sb.AppendLine($"// Generated at: {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();
            
            // 添加命名空间
            foreach (var ns in namespaces.OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine();
            
            sb.AppendLine("namespace GenBall.Event.Generated");
            sb.AppendLine("{");
            
            // 1. 事件常量定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 全局事件常量定义");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class GlobalEventConstants");
            sb.AppendLine("    {");
            
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                sb.AppendLine($"        public const string {GetSafeFieldName(evt.Module, evt.Name)} = \"{evt.FullName}\";");
            }
            
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // 2. 事件ID类（静态构造函数初始化）
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 全局事件ID");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class GlobalEventIds");
            sb.AppendLine("    {");
            
            // 声明静态字段
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                sb.AppendLine($"        public static readonly int {GetSafeFieldName(evt.Module, evt.Name)};");
            }
            sb.AppendLine();
            
            // 静态构造函数
            sb.AppendLine("        static GlobalEventIds()");
            sb.AppendLine("        {");
            foreach (var evt in events)
            {
                sb.AppendLine($"            {GetSafeFieldName(evt.Module, evt.Name)} = GetId<{evt.TypeName}>(\"{evt.FullName}\");");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 辅助方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 根据事件名获取事件ID（泛型版本）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static int GetId<T>(string eventName)");
            sb.AppendLine("        {");
            sb.AppendLine("            return ValueChangeEventArgs<T>.GetEventId(eventName);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 获取事件ID（非泛型版本，通过事件名）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static int GetId(string eventName)");
            sb.AppendLine("        {");
            sb.AppendLine("            // 默认使用object类型，适用于未预定义的事件");
            sb.AppendLine("            return GetId<object>(eventName);");
            sb.AppendLine("        }");
            
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // 3. 事件工厂（创建事件参数）
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 全局事件创建工厂");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class GlobalEventFactory");
            sb.AppendLine("    {");
            
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                sb.AppendLine($"        public static ValueChangeEventArgs<{evt.TypeName}> Create{evt.Module}{evt.Name}({evt.TypeName} value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return ValueChangeEventArgs<{evt.TypeName}>.Create(GlobalEventConstants.{GetSafeFieldName(evt.Module, evt.Name)}, value);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // 4. 核心：EventManager扩展方法
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// EventManager扩展方法（类型安全的包装器）");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class EventManagerExtensions");
            sb.AppendLine("    {");
            
            // 订阅扩展方法
            sb.AppendLine("        #region 订阅扩展方法");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>订阅 {evt.Description} 事件</summary>");
                sb.AppendLine($"        public static void Subscribe{evt.Module}{evt.Name}(this EventManager eventManager, Action<{evt.TypeName}> handler)");
                sb.AppendLine("        {");
                sb.AppendLine($"            int eventId = GlobalEventIds.{GetSafeFieldName(evt.Module, evt.Name)};");
                sb.AppendLine("            eventManager.Subscribe(eventId, (sender, args) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (args is ValueChangeEventArgs<{evt.TypeName}> valueArgs)");
                sb.AppendLine("                    handler?.Invoke(valueArgs.Value);");
                sb.AppendLine("            });");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            // 通用的订阅方法
            sb.AppendLine("        /// <summary>通用订阅方法（支持自定义事件名）</summary>");
            sb.AppendLine("        public static void SubscribeValueChange<T>(this EventManager eventManager, string eventName, Action<T> handler)");
            sb.AppendLine("        {");
            sb.AppendLine("            int eventId = ValueChangeEventArgs<T>.GetEventId(eventName);");
            sb.AppendLine("            eventManager.Subscribe(eventId, (sender, args) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                if (args is ValueChangeEventArgs<T> valueArgs)");
            sb.AppendLine("                    handler?.Invoke(valueArgs.Value);");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 取消订阅扩展方法
            sb.AppendLine("        #region 取消订阅扩展方法");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>取消订阅 {evt.Description} 事件</summary>");
                sb.AppendLine($"        public static void Unsubscribe{evt.Module}{evt.Name}(this EventManager eventManager, Action<{evt.TypeName}> handler)");
                sb.AppendLine("        {");
                sb.AppendLine($"            int eventId = GlobalEventIds.{GetSafeFieldName(evt.Module, evt.Name)};");
                sb.AppendLine("            eventManager.Unsubscribe(eventId, (sender, args) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (args is ValueChangeEventArgs<{evt.TypeName}> valueArgs)");
                sb.AppendLine("                    handler?.Invoke(valueArgs.Value);");
                sb.AppendLine("            });");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            // 通用的取消订阅方法
            sb.AppendLine("        /// <summary>通用取消订阅方法</summary>");
            sb.AppendLine("        public static void UnsubscribeValueChange<T>(this EventManager eventManager, string eventName, Action<T> handler)");
            sb.AppendLine("        {");
            sb.AppendLine("            int eventId = ValueChangeEventArgs<T>.GetEventId(eventName);");
            sb.AppendLine("            eventManager.Unsubscribe(eventId, (sender, args) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                if (args is ValueChangeEventArgs<T> valueArgs)");
            sb.AppendLine("                    handler?.Invoke(valueArgs.Value);");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 触发事件扩展方法（Fire）
            sb.AppendLine("        #region 触发事件扩展方法");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>触发 {evt.Description} 事件</summary>");
                sb.AppendLine($"        public static void Fire{evt.Module}{evt.Name}(this EventManager eventManager, {evt.TypeName} value, object sender = null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var eventArgs = GlobalEventFactory.Create{evt.Module}{evt.Name}(value);");
                sb.AppendLine("            eventManager.Fire(sender ?? eventManager, eventArgs);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            // 通用触发方法
            sb.AppendLine("        /// <summary>通用触发方法</summary>");
            sb.AppendLine("        public static void FireValueChange<T>(this EventManager eventManager, string eventName, T value, object sender = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var eventArgs = ValueChangeEventArgs<T>.Create(eventName, value);");
            sb.AppendLine("            eventManager.Fire(sender ?? eventManager, eventArgs);");
            sb.AppendLine("        }");
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 立即触发事件扩展方法（FireNow）
            sb.AppendLine("        #region 立即触发事件扩展方法");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>立即触发 {evt.Description} 事件</summary>");
                sb.AppendLine($"        public static void FireNow{evt.Module}{evt.Name}(this EventManager eventManager, {evt.TypeName} value, object sender = null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var eventArgs = GlobalEventFactory.Create{evt.Module}{evt.Name}(value);");
                sb.AppendLine("            eventManager.FireNow(sender ?? eventManager, eventArgs);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            sb.AppendLine("        /// <summary>通用立即触发方法</summary>");
            sb.AppendLine("        public static void FireNowValueChange<T>(this EventManager eventManager, string eventName, T value, object sender = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var eventArgs = ValueChangeEventArgs<T>.Create(eventName, value);");
            sb.AppendLine("            eventManager.FireNow(sender ?? eventManager, eventArgs);");
            sb.AppendLine("        }");
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 检查事件扩展方法
            sb.AppendLine("        #region 检查事件扩展方法");
            // 在 GlobalEventCodeGenerator.cs 中，修正 Check 方法的生成

// 检查事件扩展方法
            // sb.AppendLine("        #region 检查事件扩展方法");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>检查是否已订阅 {evt.Description} 事件</summary>");
                sb.AppendLine($"        public static bool Check{evt.Module}{evt.Name}(this EventManager eventManager, Action<{evt.TypeName}> handler)");
                sb.AppendLine("        {");
                sb.AppendLine($"            // 创建一个匹配 EventHandler<GameEventArgs> 签名的委托");
                sb.AppendLine($"            EventHandler<GameEventArgs> eventHandler = (sender, args) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (args is ValueChangeEventArgs<{evt.TypeName}> valueArgs)");
                sb.AppendLine("                {");
                sb.AppendLine("                    handler?.Invoke(valueArgs.Value);");
                sb.AppendLine("                }");
                sb.AppendLine("            };");
                sb.AppendLine($"            return eventManager.Check(GlobalEventIds.{GetSafeFieldName(evt.Module, evt.Name)}, eventHandler);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

// 通用的检查方法
            sb.AppendLine("        /// <summary>通用检查方法</summary>");
            sb.AppendLine("        public static bool CheckValueChange<T>(this EventManager eventManager, string eventName, Action<T> handler)");
            sb.AppendLine("        {");
            sb.AppendLine("            EventHandler<GameEventArgs> eventHandler = (sender, args) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                if (args is ValueChangeEventArgs<T> valueArgs)");
            sb.AppendLine("                {");
            sb.AppendLine("                    handler?.Invoke(valueArgs.Value);");
            sb.AppendLine("                }");
            sb.AppendLine("            };");
            sb.AppendLine("            int eventId = ValueChangeEventArgs<T>.GetEventId(eventName);");
            sb.AppendLine("            return eventManager.Check(eventId, eventHandler);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        #endregion");
            
            // sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // 5. 按模块组织的静态类 - 修正版本（不生成嵌套静态类）
            var modules = events.GroupBy(e => e.Module);
            foreach (var module in modules)
            {
                string moduleName = module.Key;
                string className = $"{moduleName}EventHelper";
                
                sb.AppendLine($"    /// <summary>{moduleName} 模块事件辅助类</summary>");
                sb.AppendLine($"    public static class {className}");
                sb.AppendLine("    {");
                
                foreach (var evt in module)
                {
                    sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                    sb.AppendLine($"        public const string {evt.Name}EventName = GlobalEventConstants.{GetSafeFieldName(evt.Module, evt.Name)};");
                    sb.AppendLine($"        public static int {evt.Name}EventId => GlobalEventIds.{GetSafeFieldName(evt.Module, evt.Name)};");
                    sb.AppendLine();
                    
                    // 创建方法
                    sb.AppendLine($"        public static ValueChangeEventArgs<{evt.TypeName}> Create{evt.Name}({evt.TypeName} value)");
                    sb.AppendLine($"            => GlobalEventFactory.Create{evt.Module}{evt.Name}(value);");
                    sb.AppendLine();
                    
                    // 订阅方法（使用扩展方法）
                    sb.AppendLine($"        public static void Subscribe{evt.Name}(EventManager eventManager, Action<{evt.TypeName}> handler)");
                    sb.AppendLine($"            => eventManager.Subscribe{evt.Module}{evt.Name}(handler);");
                    sb.AppendLine();
                    
                    // 取消订阅方法
                    sb.AppendLine($"        public static void Unsubscribe{evt.Name}(EventManager eventManager, Action<{evt.TypeName}> handler)");
                    sb.AppendLine($"            => eventManager.Unsubscribe{evt.Module}{evt.Name}(handler);");
                    sb.AppendLine();
                    
                    // 触发方法
                    sb.AppendLine($"        public static void Fire{evt.Name}(EventManager eventManager, {evt.TypeName} value, object sender = null)");
                    sb.AppendLine($"            => eventManager.Fire{evt.Module}{evt.Name}(value, sender);");
                    sb.AppendLine();
                    
                    // 立即触发方法
                    sb.AppendLine($"        public static void FireNow{evt.Name}(EventManager eventManager, {evt.TypeName} value, object sender = null)");
                    sb.AppendLine($"            => eventManager.FireNow{evt.Module}{evt.Name}(value, sender);");
                    sb.AppendLine();
                }
                
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            
            sb.AppendLine("}");
            
            // 保存文件
            string directory = "Assets/Scripts/GenBall/Event/Generated";
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);
                
            string path = Path.Combine(directory, "GlobalEventSystem.Generated.cs");
            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();
            
            Debug.Log($"全局事件系统代码生成完成！路径: {path}");
            Debug.Log($"生成了 {events.Length} 个事件，分布在 {modules.Count()} 个模块");
            
            // 显示所有使用的类型
            Debug.Log("使用的类型：");
            foreach (var type in events.Select(e => e.TypeName).Distinct())
            {
                Debug.Log($"  - {type}");
            }
            
            // 高亮显示生成的文件
            EditorUtility.FocusProjectWindow();
            Object generatedAsset = AssetDatabase.LoadAssetAtPath<Object>(path);
            Selection.activeObject = generatedAsset;
            EditorGUIUtility.PingObject(generatedAsset);
        }
        
        [MenuItem("Tools/事件/全局事件/清理生成的全局事件代码")]
        public static void CleanGeneratedCode()
        {
            string path = "Assets/Scripts/GenBall/Event/Generated/GlobalEventSystem.Generated.cs";
            if (File.Exists(path))
            {
                File.Delete(path);
                AssetDatabase.Refresh();
                Debug.Log($"已删除生成的文件: {path}");
            }
        }
        
        // 辅助方法：生成安全的字段名
        private static string GetSafeFieldName(string module, string name)
        {
            // 确保字段名是有效的C#标识符
            return $"{module}_{name}";
        }
    }
}