// EffectEventCodeGenerator.cs
using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using System;

namespace GenBall.BattleSystem.Editor
{
    public static class EffectEventCodeGenerator
    {
        [MenuItem("Tools/生成 Effect 事件系统代码")]
        public static void GenerateEffectEventCode()
        {
            try
            {
                var events = Templates.EffectEventTemplateConfig.Events;
                
                // 收集所有需要的命名空间
                var namespaces = new HashSet<string>
                {
                    "System",
                    "Yueyn.Event",
                    "Yueyn.Base.ReferencePool",
                    "GenBall.Event"
                };
                
                foreach (var evt in events)
                {
                    if (evt.ParamTypes != null)
                    {
                        foreach (var paramType in evt.ParamTypes)
                        {
                            if (paramType != null && !string.IsNullOrEmpty(paramType.Namespace))
                            {
                                namespaces.Add(paramType.Namespace);
                            }
                        }
                    }
                }
                
                // 添加Unity常用命名空间
                namespaces.Add("UnityEngine");
                
                StringBuilder sb = new StringBuilder();
                
                // 头部信息
                sb.AppendLine("// ============================================================================");
                sb.AppendLine("// Auto-generated Effect Event System - DO NOT EDIT MANUALLY");
                sb.AppendLine("// Generated by: EffectEventCodeGenerator.cs");
                sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
                sb.AppendLine("// ============================================================================");
                sb.AppendLine();
                
                // 添加命名空间
                foreach (var ns in namespaces.OrderBy(n => n))
                {
                    sb.AppendLine($"using {ns};");
                }
                sb.AppendLine();
                
                sb.AppendLine("namespace GenBall.BattleSystem.Generated");
                sb.AppendLine("{");
                
                // 1. EffectEventArgs 辅助类
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    /// EffectEventArgs 辅助类");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static class EffectEventArgsHelper");
                sb.AppendLine("    {");
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 获取事件ID");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        public static int GetEventId(string eventName)");
                sb.AppendLine("        {");
                sb.AppendLine("            return eventName.GetHashCode();");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
                
                // 2. 事件常量定义
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    /// Effect事件常量定义");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static class EffectEventConstants");
                sb.AppendLine("    {");
                
                foreach (var evt in events)
                {
                    sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                    sb.AppendLine($"        public const string {GetSafeFieldName(evt.Category, evt.Name)} = \"Effect.{evt.Category}.{evt.Name}\";");
                }
                
                sb.AppendLine("    }");
                sb.AppendLine();
                
                // 3. 事件ID类
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    /// Effect事件ID");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static class EffectEventIds");
                sb.AppendLine("    {");
                
                // 声明静态字段
                foreach (var evt in events)
                {
                    sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                    sb.AppendLine($"        public static readonly int {GetSafeFieldName(evt.Category, evt.Name)};");
                }
                sb.AppendLine();
                
                // 静态构造函数
                sb.AppendLine("        static EffectEventIds()");
                sb.AppendLine("        {");
                foreach (var evt in events)
                {
                    sb.AppendLine($"            {GetSafeFieldName(evt.Category, evt.Name)} = EffectEventArgsHelper.GetEventId(EffectEventConstants.{GetSafeFieldName(evt.Category, evt.Name)});");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
                
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 根据事件名获取事件ID");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        public static int GetId(string eventName)");
                sb.AppendLine("        {");
                sb.AppendLine("            return EffectEventArgsHelper.GetEventId(eventName);");
                sb.AppendLine("        }");
                
                sb.AppendLine("    }");
                sb.AppendLine();
                
                // 4. 事件工厂（创建事件参数）
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    /// Effect事件创建工厂");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static class EffectEventFactory");
                sb.AppendLine("    {");
                
                foreach (var evt in events)
                {
                    sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                    
                    if (evt.ParamCount == 0)
                    {
                        sb.AppendLine($"        public static EffectEventArgs<object> Create{evt.Category}{evt.Name}()");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            return EffectEventArgs<object>.Create(EffectEventConstants.{GetSafeFieldName(evt.Category, evt.Name)}, null);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 1)
                    {
                        sb.AppendLine($"        public static EffectEventArgs<{evt.ParamTypes[0].Name}> Create{evt.Category}{evt.Name}({evt.ParamTypes[0].Name} arg1)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            return EffectEventArgs<{evt.ParamTypes[0].Name}>.Create(EffectEventConstants.{GetSafeFieldName(evt.Category, evt.Name)}, arg1);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 2)
                    {
                        sb.AppendLine($"        public static EffectEventArgs<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}> Create{evt.Category}{evt.Name}({evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            return EffectEventArgs<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}>.Create(EffectEventConstants.{GetSafeFieldName(evt.Category, evt.Name)}, arg1, arg2);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 3)
                    {
                        sb.AppendLine($"        public static EffectEventArgs<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}, {evt.ParamTypes[2].Name}> Create{evt.Category}{evt.Name}({evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2, {evt.ParamTypes[2].Name} arg3)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            return EffectEventArgs<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}, {evt.ParamTypes[2].Name}>.Create(EffectEventConstants.{GetSafeFieldName(evt.Category, evt.Name)}, arg1, arg2, arg3);");
                        sb.AppendLine("        }");
                    }
                    sb.AppendLine();
                }
                
                sb.AppendLine("    }");
                sb.AppendLine();
                
                // 5. 核心：ILocalEventManager扩展方法
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    /// ILocalEventManager扩展方法（类型安全的包装器）");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine("    public static class LocalEventManagerExtensions");
                sb.AppendLine("    {");
                
                // 订阅扩展方法
                sb.AppendLine("        #region 订阅扩展方法");
                foreach (var evt in events)
                {
                    sb.AppendLine($"        /// <summary>订阅 {evt.Description} 事件</summary>");
                    
                    if (evt.ParamCount == 0)
                    {
                        sb.AppendLine($"        public static void Subscribe{evt.Category}{evt.Name}(this ILocalEventManager eventManager, Action handler)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            eventManager.Subscribe(EffectEventIds.{GetSafeFieldName(evt.Category, evt.Name)}, (sender, args) =>");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                if (args is EffectEventArgs<object>)");
                        sb.AppendLine("                    handler?.Invoke();");
                        sb.AppendLine("            });");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 1)
                    {
                        sb.AppendLine($"        public static void Subscribe{evt.Category}{evt.Name}(this ILocalEventManager eventManager, Action<{evt.ParamTypes[0].Name}> handler)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            eventManager.Subscribe(EffectEventIds.{GetSafeFieldName(evt.Category, evt.Name)}, (sender, args) =>");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                if (args is EffectEventArgs<{evt.ParamTypes[0].Name}> effectArgs)");
                        sb.AppendLine("                    handler?.Invoke(effectArgs.Args);");
                        sb.AppendLine("            });");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 2)
                    {
                        sb.AppendLine($"        public static void Subscribe{evt.Category}{evt.Name}(this ILocalEventManager eventManager, Action<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}> handler)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            eventManager.Subscribe(EffectEventIds.{GetSafeFieldName(evt.Category, evt.Name)}, (sender, args) =>");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                if (args is EffectEventArgs<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}> effectArgs)");
                        sb.AppendLine("                    handler?.Invoke(effectArgs.Args1, effectArgs.Args2);");
                        sb.AppendLine("            });");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 3)
                    {
                        sb.AppendLine($"        public static void Subscribe{evt.Category}{evt.Name}(this ILocalEventManager eventManager, Action<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}, {evt.ParamTypes[2].Name}> handler)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            eventManager.Subscribe(EffectEventIds.{GetSafeFieldName(evt.Category, evt.Name)}, (sender, args) =>");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                if (args is EffectEventArgs<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}, {evt.ParamTypes[2].Name}> effectArgs)");
                        sb.AppendLine("                    handler?.Invoke(effectArgs.Args1, effectArgs.Args2, effectArgs.Args3);");
                        sb.AppendLine("            });");
                        sb.AppendLine("        }");
                    }
                    sb.AppendLine();
                }
                
                sb.AppendLine("        #endregion");
                sb.AppendLine();
                
                // 取消订阅扩展方法
                sb.AppendLine("        #region 取消订阅扩展方法");
                foreach (var evt in events)
                {
                    sb.AppendLine($"        /// <summary>取消订阅 {evt.Description} 事件</summary>");
                    
                    if (evt.ParamCount == 0)
                    {
                        sb.AppendLine($"        public static void Unsubscribe{evt.Category}{evt.Name}(this ILocalEventManager eventManager, Action handler)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            eventManager.Unsubscribe(EffectEventIds.{GetSafeFieldName(evt.Category, evt.Name)}, (sender, args) =>");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                if (args is EffectEventArgs<object>)");
                        sb.AppendLine("                    handler?.Invoke();");
                        sb.AppendLine("            });");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 1)
                    {
                        sb.AppendLine($"        public static void Unsubscribe{evt.Category}{evt.Name}(this ILocalEventManager eventManager, Action<{evt.ParamTypes[0].Name}> handler)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            eventManager.Unsubscribe(EffectEventIds.{GetSafeFieldName(evt.Category, evt.Name)}, (sender, args) =>");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                if (args is EffectEventArgs<{evt.ParamTypes[0].Name}> effectArgs)");
                        sb.AppendLine("                    handler?.Invoke(effectArgs.Args);");
                        sb.AppendLine("            });");
                        sb.AppendLine("        }");
                    }
                    sb.AppendLine();
                }
                
                sb.AppendLine("        #endregion");
                sb.AppendLine();
                
                // 触发事件扩展方法（FireEvent）
                sb.AppendLine("        #region 触发事件扩展方法（排队）");
                foreach (var evt in events)
                {
                    sb.AppendLine($"        /// <summary>触发 {evt.Description} 事件（排队）</summary>");
                    
                    if (evt.ParamCount == 0)
                    {
                        sb.AppendLine($"        public static void FireEvent{evt.Category}{evt.Name}(this ILocalEventManager eventManager, object sender = null)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Category}{evt.Name}();");
                        sb.AppendLine("            eventManager.FireEvent(sender ?? eventManager, eventArgs);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 1)
                    {
                        sb.AppendLine($"        public static void FireEvent{evt.Category}{evt.Name}(this ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, object sender = null)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Category}{evt.Name}(arg1);");
                        sb.AppendLine("            eventManager.FireEvent(sender ?? eventManager, eventArgs);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 2)
                    {
                        sb.AppendLine($"        public static void FireEvent{evt.Category}{evt.Name}(this ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2, object sender = null)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Category}{evt.Name}(arg1, arg2);");
                        sb.AppendLine("            eventManager.FireEvent(sender ?? eventManager, eventArgs);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 3)
                    {
                        sb.AppendLine($"        public static void FireEvent{evt.Category}{evt.Name}(this ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2, {evt.ParamTypes[2].Name} arg3, object sender = null)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Category}{evt.Name}(arg1, arg2, arg3);");
                        sb.AppendLine("            eventManager.FireEvent(sender ?? eventManager, eventArgs);");
                        sb.AppendLine("        }");
                    }
                    sb.AppendLine();
                }
                
                sb.AppendLine("        #endregion");
                sb.AppendLine();
                
                // 立即触发事件扩展方法（FireNow）
                sb.AppendLine("        #region 立即触发事件扩展方法（立即执行）");
                foreach (var evt in events)
                {
                    sb.AppendLine($"        /// <summary>立即触发 {evt.Description} 事件</summary>");
                    
                    if (evt.ParamCount == 0)
                    {
                        sb.AppendLine($"        public static void FireNow{evt.Category}{evt.Name}(this ILocalEventManager eventManager, object sender = null)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Category}{evt.Name}();");
                        sb.AppendLine("            eventManager.FireNow(sender ?? eventManager, eventArgs);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 1)
                    {
                        sb.AppendLine($"        public static void FireNow{evt.Category}{evt.Name}(this ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, object sender = null)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Category}{evt.Name}(arg1);");
                        sb.AppendLine("            eventManager.FireNow(sender ?? eventManager, eventArgs);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 2)
                    {
                        sb.AppendLine($"        public static void FireNow{evt.Category}{evt.Name}(this ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2, object sender = null)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Category}{evt.Name}(arg1, arg2);");
                        sb.AppendLine("            eventManager.FireNow(sender ?? eventManager, eventArgs);");
                        sb.AppendLine("        }");
                    }
                    else if (evt.ParamCount == 3)
                    {
                        sb.AppendLine($"        public static void FireNow{evt.Category}{evt.Name}(this ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2, {evt.ParamTypes[2].Name} arg3, object sender = null)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Category}{evt.Name}(arg1, arg2, arg3);");
                        sb.AppendLine("            eventManager.FireNow(sender ?? eventManager, eventArgs);");
                        sb.AppendLine("        }");
                    }
                    sb.AppendLine();
                }
                
                sb.AppendLine("        #endregion");
                sb.AppendLine();
                
                sb.AppendLine("    }");
                sb.AppendLine();
                
                // 6. 按类别组织的静态辅助类
                var categories = events.GroupBy(e => e.Category);
                foreach (var category in categories)
                {
                    string className = $"{category.Key}EffectEvents";
                    sb.AppendLine($"    /// <summary>{category.Key} 相关Effect事件</summary>");
                    sb.AppendLine($"    public static class {className}");
                    sb.AppendLine("    {");
                    
                    foreach (var evt in category)
                    {
                        sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                        sb.AppendLine($"        public static class {evt.Name}");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            public const string Name = EffectEventConstants.{GetSafeFieldName(evt.Category, evt.Name)};");
                        sb.AppendLine($"            public static int Id => EffectEventIds.{GetSafeFieldName(evt.Category, evt.Name)};");
                        sb.AppendLine();
                        
                        // 创建方法
                        if (evt.ParamCount == 0)
                        {
                            sb.AppendLine($"            public static EffectEventArgs<object> Create()");
                            sb.AppendLine($"                => EffectEventFactory.Create{evt.Category}{evt.Name}();");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void Subscribe(ILocalEventManager eventManager, Action handler)");
                            sb.AppendLine($"                => eventManager.Subscribe{evt.Category}{evt.Name}(handler);");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void FireEvent(ILocalEventManager eventManager, object sender = null)");
                            sb.AppendLine($"                => eventManager.FireEvent{evt.Category}{evt.Name}(sender);");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void FireNow(ILocalEventManager eventManager, object sender = null)");
                            sb.AppendLine($"                => eventManager.FireNow{evt.Category}{evt.Name}(sender);");
                        }
                        else if (evt.ParamCount == 1)
                        {
                            sb.AppendLine($"            public static EffectEventArgs<{evt.ParamTypes[0].Name}> Create({evt.ParamTypes[0].Name} arg1)");
                            sb.AppendLine($"                => EffectEventFactory.Create{evt.Category}{evt.Name}(arg1);");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void Subscribe(ILocalEventManager eventManager, Action<{evt.ParamTypes[0].Name}> handler)");
                            sb.AppendLine($"                => eventManager.Subscribe{evt.Category}{evt.Name}(handler);");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void FireEvent(ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, object sender = null)");
                            sb.AppendLine($"                => eventManager.FireEvent{evt.Category}{evt.Name}(arg1, sender);");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void FireNow(ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, object sender = null)");
                            sb.AppendLine($"                => eventManager.FireNow{evt.Category}{evt.Name}(arg1, sender);");
                        }
                        else if (evt.ParamCount == 2)
                        {
                            sb.AppendLine($"            public static EffectEventArgs<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}> Create({evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2)");
                            sb.AppendLine($"                => EffectEventFactory.Create{evt.Category}{evt.Name}(arg1, arg2);");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void Subscribe(ILocalEventManager eventManager, Action<{evt.ParamTypes[0].Name}, {evt.ParamTypes[1].Name}> handler)");
                            sb.AppendLine($"                => eventManager.Subscribe{evt.Category}{evt.Name}(handler);");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void FireEvent(ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2, object sender = null)");
                            sb.AppendLine($"                => eventManager.FireEvent{evt.Category}{evt.Name}(arg1, arg2, sender);");
                            sb.AppendLine();
                            
                            sb.AppendLine($"            public static void FireNow(ILocalEventManager eventManager, {evt.ParamTypes[0].Name} arg1, {evt.ParamTypes[1].Name} arg2, object sender = null)");
                            sb.AppendLine($"                => eventManager.FireNow{evt.Category}{evt.Name}(arg1, arg2, sender);");
                        }
                        
                        sb.AppendLine("        }");
                        sb.AppendLine();
                    }
                    
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
                
                sb.AppendLine("}");
                
                // 保存文件
                string directory = "Assets/Scripts/GenBall/BattleSystem/Generated";
                if (!Directory.Exists(directory))
                    Directory.CreateDirectory(directory);
                    
                string path = Path.Combine(directory, "EffectEvents.Generated.cs");
                File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
                AssetDatabase.Refresh();
                
                Debug.Log($"Effect事件系统代码生成完成！路径: {path}");
                Debug.Log($"生成了 {events.Length} 个事件，分布在 {categories.Count()} 个分类");
                
                // 显示所有使用的类型
                Debug.Log("使用的类型：");
                var allTypes = events
                    .Where(e => e.ParamTypes != null)
                    .SelectMany(e => e.ParamTypes)
                    .Distinct()
                    .OrderBy(t => t.Name);
                
                foreach (var type in allTypes)
                {
                    Debug.Log($"  - {type.Name} (来自 {type.Namespace})");
                }
                
                // 高亮显示生成的文件
                EditorUtility.FocusProjectWindow();
                UnityEngine.Object generatedAsset = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(path);
                Selection.activeObject = generatedAsset;
                EditorGUIUtility.PingObject(generatedAsset);
            }
            catch (Exception ex)
            {
                Debug.LogError($"生成Effect事件代码时出错: {ex.Message}\n{ex.StackTrace}");
            }
        }
        
        [MenuItem("Tools/清理生成的Effect事件代码")]
        public static void CleanGeneratedCode()
        {
            string path = "Assets/Scripts/GenBall/BattleSystem/Generated/EffectEvents.Generated.cs";
            if (File.Exists(path))
            {
                File.Delete(path);
                AssetDatabase.Refresh();
                Debug.Log($"已删除生成的文件: {path}");
            }
        }
        
        // 辅助方法：生成安全的字段名
        private static string GetSafeFieldName(string category, string name)
        {
            // 确保字段名是有效的C#标识符
            return $"{category}_{name}";
        }
    }
}