// EventCodeGenerator.cs - 修正版本
using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Linq;

namespace GenBall.BattleSystem.Editor
{
    public static class EventCodeGenerator
    {
        [MenuItem("Tools/事件/Effect/生成 Effect 事件代码")]
        public static void GenerateEventCode()
        {
            var events = Templates.EventTemplateConfig.Events;
            
            StringBuilder sb = new StringBuilder();
            
            // 头部
            sb.AppendLine("// ============================================================================");
            sb.AppendLine("// Auto-generated Effect Events - DO NOT EDIT MANUALLY");
            sb.AppendLine("// Generated by: EventCodeGenerator.cs");
            sb.AppendLine($"// Generated at: {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using Yueyn.Event;");
            sb.AppendLine("using Yueyn.Base.ReferencePool;");
            sb.AppendLine("using GenBall.Player;");
            sb.AppendLine("using GenBall.BattleSystem.Weapons;");
            sb.AppendLine();
            
            sb.AppendLine("namespace GenBall.BattleSystem.Generated");
            sb.AppendLine("{");
            
            // 1. 事件常量 - 保留为编译时常量
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Effect事件常量定义");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class EffectEventConstants");
            sb.AppendLine("    {");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                sb.AppendLine($"        public const string {evt.Name} = \"Effect.{evt.Name}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // 2. 事件ID - 改为属性或静态字段初始值
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Effect事件ID");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class EffectEventIds");
            sb.AppendLine("    {");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                // 使用静态只读字段，在静态构造函数中初始化
                sb.AppendLine($"        public static readonly int {evt.Name};");
            }
            sb.AppendLine();
            // 静态构造函数
            sb.AppendLine("        static EffectEventIds()");
            sb.AppendLine("        {");
            foreach (var evt in events)
            {
                sb.AppendLine($"            {evt.Name} = EffectEventArgs.GetEventId(EffectEventConstants.{evt.Name});");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // 3. 事件工厂
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Effect事件创建工厂");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class EffectEventFactory");
            sb.AppendLine("    {");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                
                if (evt.ParamCount == 0)
                {
                    sb.AppendLine($"        public static EffectEventArgs Create{evt.Name}()");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return EffectEventArgs<object>.Create(EffectEventConstants.{evt.Name}, null);");
                    sb.AppendLine("        }");
                }
                else if (evt.ParamCount == 1)
                {
                    sb.AppendLine($"        public static EffectEventArgs<{evt.ParamTypes[0]}> Create{evt.Name}({evt.ParamTypes[0]} arg1)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return EffectEventArgs<{evt.ParamTypes[0]}>.Create(EffectEventConstants.{evt.Name}, arg1);");
                    sb.AppendLine("        }");
                }
                else if (evt.ParamCount == 2)
                {
                    sb.AppendLine($"        public static EffectEventArgs<{evt.ParamTypes[0]}, {evt.ParamTypes[1]}> Create{evt.Name}({evt.ParamTypes[0]} arg1, {evt.ParamTypes[1]} arg2)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return EffectEventArgs<{evt.ParamTypes[0]}, {evt.ParamTypes[1]}>.Create(EffectEventConstants.{evt.Name}, arg1, arg2);");
                    sb.AppendLine("        }");
                }
                sb.AppendLine();
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // 4. 扩展方法
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Effect事件系统扩展方法");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class EffectEventExtensions");
            sb.AppendLine("    {");
            
            // 订阅扩展方法
            sb.AppendLine("        #region 订阅扩展方法");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                
                if (evt.ParamCount == 0)
                {
                    sb.AppendLine($"        public static void Subscribe{evt.Name}(this IEffectable effectable, Action handler)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            effectable.Subscribe(EffectEventIds.{evt.Name}, (sender, args) => handler?.Invoke());");
                    sb.AppendLine("        }");
                }
                else if (evt.ParamCount == 1)
                {
                    sb.AppendLine($"        public static void Subscribe{evt.Name}(this IEffectable effectable, Action<{evt.ParamTypes[0]}> handler)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            effectable.Subscribe(EffectEventIds.{evt.Name}, (sender, args) =>");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                if (args is EffectEventArgs<{evt.ParamTypes[0]}> effectArgs)");
                    sb.AppendLine("                    handler?.Invoke(effectArgs.Args);");
                    sb.AppendLine("            });");
                    sb.AppendLine("        }");
                }
                else if (evt.ParamCount == 2)
                {
                    sb.AppendLine($"        public static void Subscribe{evt.Name}(this IEffectable effectable, Action<{evt.ParamTypes[0]}, {evt.ParamTypes[1]}> handler)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            effectable.Subscribe(EffectEventIds.{evt.Name}, (sender, args) =>");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                if (args is EffectEventArgs<{evt.ParamTypes[0]}, {evt.ParamTypes[1]}> effectArgs)");
                    sb.AppendLine("                    handler?.Invoke(effectArgs.Args1, effectArgs.Args2);");
                    sb.AppendLine("            });");
                    sb.AppendLine("        }");
                }
                sb.AppendLine();
            }
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 触发扩展方法
            sb.AppendLine("        #region 触发扩展方法");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                
                if (evt.ParamCount == 0)
                {
                    sb.AppendLine($"        public static void Fire{evt.Name}(this IEffectable effectable, object sender = null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Name}();");
                    sb.AppendLine("            if (effectable is WeaponBase weapon)");
                    sb.AppendLine("                weapon.FireEvent(sender ?? effectable, eventArgs);");
                    sb.AppendLine("        }");
                }
                else if (evt.ParamCount == 1)
                {
                    sb.AppendLine($"        public static void Fire{evt.Name}(this IEffectable effectable, {evt.ParamTypes[0]} arg1, object sender = null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Name}(arg1);");
                    sb.AppendLine("            if (effectable is WeaponBase weapon)");
                    sb.AppendLine("                weapon.FireEvent(sender ?? effectable, eventArgs);");
                    sb.AppendLine("        }");
                }
                else if (evt.ParamCount == 2)
                {
                    sb.AppendLine($"        public static void Fire{evt.Name}(this IEffectable effectable, {evt.ParamTypes[0]} arg1, {evt.ParamTypes[1]} arg2, object sender = null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            var eventArgs = EffectEventFactory.Create{evt.Name}(arg1, arg2);");
                    sb.AppendLine("            if (effectable is WeaponBase weapon)");
                    sb.AppendLine("                weapon.FireEvent(sender ?? effectable, eventArgs);");
                    sb.AppendLine("        }");
                }
                sb.AppendLine();
            }
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 取消订阅扩展方法
            sb.AppendLine("        #region 取消订阅扩展方法");
            foreach (var evt in events)
            {
                sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                
                if (evt.ParamCount == 0)
                {
                    sb.AppendLine($"        public static void Unsubscribe{evt.Name}(this IEffectable effectable, Action handler)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            effectable.Unsubscribe(EffectEventIds.{evt.Name}, (sender, args) => handler?.Invoke());");
                    sb.AppendLine("        }");
                }
                else if (evt.ParamCount == 1)
                {
                    sb.AppendLine($"        public static void Unsubscribe{evt.Name}(this IEffectable effectable, Action<{evt.ParamTypes[0]}> handler)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            effectable.Unsubscribe(EffectEventIds.{evt.Name}, (sender, args) =>");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                if (args is EffectEventArgs<{evt.ParamTypes[0]}> effectArgs)");
                    sb.AppendLine("                    handler?.Invoke(effectArgs.Args);");
                    sb.AppendLine("            });");
                    sb.AppendLine("        }");
                }
                sb.AppendLine();
            }
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 辅助方法：根据事件名获取ID
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 根据事件名获取事件ID");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static int GetEventId(string eventName) => EffectEventArgs.GetEventId(eventName);");
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // 5. 按类别组织的静态类
            var categories = events.GroupBy(e => e.Category);
            foreach (var category in categories)
            {
                string className = $"{category.Key}Events";
                sb.AppendLine($"    /// <summary>{category.Key} 相关事件</summary>");
                sb.AppendLine($"    public static class {className}");
                sb.AppendLine("    {");
                
                foreach (var evt in category)
                {
                    sb.AppendLine($"        /// <summary>{evt.Description}</summary>");
                    sb.AppendLine($"        public static class {evt.Name}");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            public const string Name = EffectEventConstants.{evt.Name};");
                    sb.AppendLine($"            public static int Id => EffectEventIds.{evt.Name};"); // 改为属性
                    sb.AppendLine();
                    
                    if (evt.ParamCount == 0)
                    {
                        sb.AppendLine("            public static EffectEventArgs Create() => EffectEventFactory.Create" + evt.Name + "();");
                        sb.AppendLine($"            public static void Subscribe(IEffectable effectable, Action handler) => effectable.Subscribe{evt.Name}(handler);");
                        sb.AppendLine($"            public static void Fire(IEffectable effectable, object sender = null) => effectable.Fire{evt.Name}(sender);");
                    }
                    else if (evt.ParamCount == 1)
                    {
                        sb.AppendLine($"            public static EffectEventArgs<{evt.ParamTypes[0]}> Create({evt.ParamTypes[0]} arg1) => EffectEventFactory.Create{evt.Name}(arg1);");
                        sb.AppendLine($"            public static void Subscribe(IEffectable effectable, Action<{evt.ParamTypes[0]}> handler) => effectable.Subscribe{evt.Name}(handler);");
                        sb.AppendLine($"            public static void Fire(IEffectable effectable, {evt.ParamTypes[0]} arg1, object sender = null) => effectable.Fire{evt.Name}(arg1, sender);");
                    }
                    else if (evt.ParamCount == 2)
                    {
                        sb.AppendLine($"            public static EffectEventArgs<{evt.ParamTypes[0]}, {evt.ParamTypes[1]}> Create({evt.ParamTypes[0]} arg1, {evt.ParamTypes[1]} arg2) => EffectEventFactory.Create{evt.Name}(arg1, arg2);");
                        sb.AppendLine($"            public static void Subscribe(IEffectable effectable, Action<{evt.ParamTypes[0]}, {evt.ParamTypes[1]}> handler) => effectable.Subscribe{evt.Name}(handler);");
                        sb.AppendLine($"            public static void Fire(IEffectable effectable, {evt.ParamTypes[0]} arg1, {evt.ParamTypes[1]} arg2, object sender = null) => effectable.Fire{evt.Name}(arg1, arg2, sender);");
                    }
                    
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            
            sb.AppendLine("}");
            
            // 保存文件
            string path = "Assets/Scripts/GenBall/BattleSystem/Generated/EffectEvents.Generated.cs";
            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();
            
            Debug.Log($"事件代码生成完成！路径: {path}");
            Debug.Log($"生成了 {events.Length} 个事件");
            
            // 在编辑器中高亮显示生成的文件
            EditorUtility.FocusProjectWindow();
            Object generatedAsset = AssetDatabase.LoadAssetAtPath<Object>(path);
            Selection.activeObject = generatedAsset;
            EditorGUIUtility.PingObject(generatedAsset);
        }
        
        [MenuItem("Tools/事件/Effect/清理生成的代码")]
        public static void CleanGeneratedCode()
        {
            string path = "Assets/Scripts/GenBall/BattleSystem/Generated/EffectEvents.Generated.cs";
            if (File.Exists(path))
            {
                File.Delete(path);
                AssetDatabase.Refresh();
                Debug.Log($"已删除生成的文件: {path}");
            }
        }
    }
    
    
}