using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace GenBall.Utils.CodeGenerator.UI.Editor
{
    /// <summary>
    /// Generates View.Generated.cs and Logic.Generated.cs C# code from scanned bindings.
    /// View uses editor-persisted component references (no runtime transform.Find).
    /// </summary>
    public static class UiBindingCodeGenerator
    {
        public static string GenerateViewCode(
            string formName,
            string prefabPath,
            List<UiPrefabScanner.BindingInfo> bindings,
            string namespaceName = "GenBall.UI",
            string baseClass = "Yueyn.UI.UIBusinessFormBase",
            UiViewBinding.ViewType viewType = UiViewBinding.ViewType.Form)
        {
            var sb = new StringBuilder();

            // Header
            sb.AppendLine($"// Auto-generated by UiCodeGenerator on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// Source prefab: {prefabPath}");
            sb.AppendLine("// DO NOT EDIT MANUALLY");
            sb.AppendLine();

            // Using statements
            var neededUsings = new HashSet<string> { "UnityEngine", "GenBall.Utils.CodeGenerator.UI" };
            foreach (var b in bindings)
            {
                var ns = GetNamespace(b.fullTypeName);
                if (!string.IsNullOrEmpty(ns) && ns != "UnityEngine")
                    neededUsings.Add(ns);
            }

            if (baseClass.StartsWith("Yueyn"))
                neededUsings.Add("Yueyn.UI");

            foreach (var ns in neededUsings.OrderBy(n => n))
                sb.AppendLine($"using {ns};");

            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            var shortBase = baseClass.Split('.').Last();
            sb.AppendLine($"    public partial class {formName}View : {shortBase}");
            sb.AppendLine("    {");
            sb.AppendLine("        private UiViewBinding _binding;");
            sb.AppendLine();

            if (bindings.Count == 0)
            {
                sb.AppendLine("        // (no bindings detected)");
            }
            else
            {
                sb.AppendLine("        // -- Bound Controls --");
                foreach (var b in bindings)
                {
                    if (!b.included) continue;
                    sb.AppendLine($"        public {b.componentType} {b.propertyName} {{ get; private set; }}");
                }
            }

            sb.AppendLine();
            sb.AppendLine("        // -- Auto-Binding --");
            sb.AppendLine();

            if (viewType == UiViewBinding.ViewType.Form)
            {
                sb.AppendLine("        protected override void DoBusinessStart()");
                sb.AppendLine("        {");
                sb.AppendLine("            base.DoBusinessStart();");
                sb.AppendLine("            BindControls();");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine("        protected virtual void Awake()");
                sb.AppendLine("        {");
                sb.AppendLine("            BindControls();");
                sb.AppendLine("        }");
            }

            sb.AppendLine();
            sb.AppendLine("        private void BindControls()");
            sb.AppendLine("        {");

            if (bindings.Count == 0 || bindings.All(b => !b.included))
            {
                sb.AppendLine("            // No controls to bind");
            }
            else
            {
                sb.AppendLine("            _binding = GetComponent<UiViewBinding>();");
                var included = bindings.Where(b => b.included).ToList();
                int maxLen = included.Max(b => b.propertyName.Length);
                foreach (var b in included)
                {
                    var pad = new string(' ', maxLen - b.propertyName.Length);
                    sb.AppendLine(
                        $"            {b.propertyName}{pad} = _binding.GetBinding<{b.componentType}>(\"{b.propertyName}\");");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        public static string GenerateLogicCode(
            string formName,
            string prefabPath,
            string formType,
            string namespaceName = "GenBall.UI",
            string baseClass = "Yueyn.UI.BusinessFormLogic",
            UiViewBinding.ViewType viewType = UiViewBinding.ViewType.Form)
        {
            var sb = new StringBuilder();

            // Header
            sb.AppendLine($"// Auto-generated by UiCodeGenerator on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// Source prefab: {prefabPath}");
            sb.AppendLine("// DO NOT EDIT MANUALLY");
            sb.AppendLine();

            if (viewType == UiViewBinding.ViewType.Form)
            {
                sb.AppendLine("using Yueyn.UI;");
            }
            else
            {
                // Part logic: minimal usings
                if (!string.IsNullOrEmpty(baseClass) && baseClass.StartsWith("Yueyn"))
                    sb.AppendLine("using Yueyn.UI;");
            }

            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            if (viewType == UiViewBinding.ViewType.Part && string.IsNullOrEmpty(baseClass))
            {
                // Part with no logic base class — generate a stub
                sb.AppendLine($"    public partial class {formName}Logic");
                sb.AppendLine("    {");
                sb.AppendLine($"        public {formName}View View {{ get; set; }}");
                sb.AppendLine("    }");
            }
            else
            {
                var shortBase = baseClass.Split('.').Last();
                sb.AppendLine($"    public partial class {formName}Logic : {shortBase}");
                sb.AppendLine("    {");

                if (viewType == UiViewBinding.ViewType.Form)
                {
                    sb.AppendLine("        // -- Form Configuration --");
                    sb.AppendLine();
                    sb.AppendLine("        public override string PrefabPath =>");
                    sb.AppendLine($"            \"{prefabPath}\";");
                    sb.AppendLine();
                    sb.AppendLine($"        public override UIFormType FormType => UIFormType.{formType};");
                    sb.AppendLine();
                    sb.AppendLine("        // -- View Reference --");
                    sb.AppendLine();
                    sb.AppendLine($"        public {formName}View View {{ get; private set; }}");
                    sb.AppendLine();
                    sb.AppendLine("        // -- Lifecycle --");
                    sb.AppendLine();
                    sb.AppendLine("        public override void OnCreate()");
                    sb.AppendLine("        {");
                    sb.AppendLine("            base.OnCreate();");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        protected override void OnFormBound(UIFormScript form)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            base.OnFormBound(form);");
                    sb.AppendLine($"            View = form.GetComponentInChildren<{formName}View>();");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        protected override void OnFormUnbound(UIFormScript form)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            View = null;");
                    sb.AppendLine("            base.OnFormUnbound(form);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        // -- Convenience --");
                    sb.AppendLine();
                    sb.AppendLine($"        public static {formName}Logic Open()");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return BusinessLogicManager.Instance.CreateFormLogic<{formName}Logic>();");
                    sb.AppendLine("        }");
                }
                else
                {
                    // Part logic
                    sb.AppendLine($"        public {formName}View View {{ get; set; }}");
                    sb.AppendLine();
                    sb.AppendLine("        public virtual void OnCreate()");
                    sb.AppendLine("        {");
                    sb.AppendLine("        }");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Returns the View file name: {formName}View.Generated.cs
        /// </summary>
        public static string GetViewFileName(string formName)
        {
            return $"{formName}View.Generated.cs";
        }

        /// <summary>
        /// Returns the Logic file name: {formName}Logic.Generated.cs
        /// </summary>
        public static string GetLogicFileName(string formName)
        {
            return $"{formName}Logic.Generated.cs";
        }

        public static void GenerateAll(
            UiPrefabScanner.ScanResult scanResult,
            string formName,
            string formType,
            string outputDir,
            string namespaceName = "GenBall.UI",
            string viewBaseClass = "Yueyn.UI.UIBusinessFormBase",
            string logicBaseClass = "Yueyn.UI.BusinessFormLogic",
            UiViewBinding.ViewType viewType = UiViewBinding.ViewType.Form,
            bool force = false)
        {
            var viewCode = GenerateViewCode(formName, scanResult.prefabPath, scanResult.bindings,
                namespaceName, viewBaseClass, viewType);
            var logicCode = GenerateLogicCode(formName, scanResult.prefabPath, formType,
                namespaceName, logicBaseClass, viewType);

            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            var viewPath = Path.Combine(outputDir, GetViewFileName(formName));
            var logicPath = Path.Combine(outputDir, GetLogicFileName(formName));

            if (File.Exists(viewPath) && !force)
                Debug.LogWarning($"[UiCodeGenerator] Skipped (exists, use force): {viewPath}");
            else
                File.WriteAllText(viewPath, viewCode, Encoding.UTF8);

            if (File.Exists(logicPath) && !force)
                Debug.LogWarning($"[UiCodeGenerator] Skipped (exists, use force): {logicPath}");
            else
                File.WriteAllText(logicPath, logicCode, Encoding.UTF8);

            AssetDatabase.Refresh();

            Debug.Log($"[UiCodeGenerator] Generated for {formName}:\n  {viewPath}\n  {logicPath}");
        }

        private static string GetNamespace(string fullTypeName)
        {
            var lastDot = fullTypeName.LastIndexOf('.');
            if (lastDot <= 0) return "";
            return fullTypeName.Substring(0, lastDot);
        }
    }
}
