"""C# code generator — produces View.cs and Logic.cs from binding entries."""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from .prefab_parser import BindingEntry


def _format_datetime() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def generate_view_code(
    form_name: str,
    prefab_path: str,
    bindings: List[BindingEntry],
    namespace: str = "GenBall.UI",
    base_class: str = "Yueyn.UI.UIBusinessFormBase",
) -> str:
    """Generate C# View code.

    Args:
        form_name: e.g. "MainHud"
        prefab_path: Project-relative prefab path.
        bindings: List of BindingEntry objects.
        namespace: C# namespace for the generated class.
        base_class: Fully qualified base class name.

    Returns:
        Complete C# source code for the View file.
    """
    # Collect required using statements
    usings = _collect_usings(bindings, base_class)

    # Build property declarations
    properties = _build_properties(bindings)

    # Build BindControls body
    bind_body = _build_bind_controls(bindings)

    code = f"""// Auto-generated by UiCodeGenerator on {_format_datetime()}
// Source prefab: {prefab_path}
// DO NOT EDIT MANUALLY

{usings}

namespace {namespace}
{{
    public partial class {form_name}View : {_short_name(base_class)}
    {{
        // -- Bound Controls --
{properties}

        // -- Auto-Binding --

        protected override void DoBusinessStart()
        {{
            base.DoBusinessStart();
            BindControls();
        }}

        private void BindControls()
        {{
{bind_body}
        }}
    }}
}}
"""
    return code


def generate_logic_code(
    form_name: str,
    prefab_path: str,
    form_type: str,
    namespace: str = "GenBall.UI",
    base_class: str = "Yueyn.UI.BusinessFormLogic",
) -> str:
    """Generate C# Logic code.

    Args:
        form_name: e.g. "MainHud"
        prefab_path: Project-relative prefab path.
        form_type: UIFormType value ("Persistent", "Popup", "Transition").
        namespace: C# namespace for the generated class.
        base_class: Fully qualified base class name.

    Returns:
        Complete C# source code for the Logic file.
    """
    code = f"""// Auto-generated by UiCodeGenerator on {_format_datetime()}
// Source prefab: {prefab_path}
// DO NOT EDIT MANUALLY

using Yueyn.UI;

namespace {namespace}
{{
    public partial class {form_name}Logic : {_short_name(base_class)}
    {{
        // -- Form Configuration --

        public override string PrefabPath =>
            "{prefab_path}";

        public override UIFormType FormType => UIFormType.{form_type};

        // -- View Reference --

        public {form_name}View View {{ get; private set; }}

        // -- Lifecycle --

        public override void OnCreate()
        {{
            base.OnCreate();
        }}

        protected override void OnFormBound(UIFormScript form)
        {{
            base.OnFormBound(form);
            View = form.GetComponentInChildren<{form_name}View>();
        }}

        protected override void OnFormUnbound(UIFormScript form)
        {{
            View = null;
            base.OnFormUnbound(form);
        }}

        // -- Convenience --

        public static {form_name}Logic Open()
        {{
            return BusinessLogicManager.Instance.CreateFormLogic<{form_name}Logic>();
        }}
    }}
}}
"""
    return code


def generate_all(
    form_name: str,
    prefab_path: str,
    bindings: List[BindingEntry],
    form_type: str = "Popup",
    namespace: str = "GenBall.UI",
    view_base_class: str = "Yueyn.UI.UIBusinessFormBase",
    logic_base_class: str = "Yueyn.UI.BusinessFormLogic",
) -> Dict[str, str]:
    """Generate both View and Logic code.

    Returns:
        Dict with keys "view" and "logic".
    """
    return {
        "view": generate_view_code(
            form_name=form_name,
            prefab_path=prefab_path,
            bindings=bindings,
            namespace=namespace,
            base_class=view_base_class,
        ),
        "logic": generate_logic_code(
            form_name=form_name,
            prefab_path=prefab_path,
            form_type=form_type,
            namespace=namespace,
            base_class=logic_base_class,
        ),
    }


def write_generated_files(
    output_dir: str,
    form_name: str,
    view_code: str,
    logic_code: str,
    force: bool = False,
) -> tuple:
    """Write generated code to files.

    Args:
        output_dir: Output directory (e.g. "Assets/Scripts/GenBall/UI/MainHud").
        form_name: Form name (used in filenames).
        view_code: View C# source.
        logic_code: Logic C# source.
        force: Overwrite existing files.

    Returns:
        Tuple of (view_path, logic_path, skipped_files).
    """
    os.makedirs(output_dir, exist_ok=True)

    view_path = os.path.join(output_dir, f"{form_name}.View.cs")
    logic_path = os.path.join(output_dir, f"{form_name}.Logic.cs")
    skipped = []

    for path, code in [(view_path, view_code), (logic_path, logic_code)]:
        if os.path.exists(path) and not force:
            skipped.append(path)
            continue
        with open(path, "w", encoding="utf-8") as f:
            f.write(code)

    return view_path, logic_path, skipped


# ─── Private Helpers ──────────────────────────────────────────────────

def _short_name(full_name: str) -> str:
    """Extract short class name from fully qualified name."""
    return full_name.rsplit(".", 1)[-1]


def _collect_usings(bindings: List[BindingEntry], base_class: str) -> str:
    """Collect required using statements."""
    needed = set()

    # Base class using
    if base_class.startswith("Yueyn"):
        needed.add("using Yueyn.UI;")

    # Component usings
    for entry in bindings:
        ns = entry.using_namespace
        if ns and ns != "UnityEngine":
            needed.add(f"using {ns};")

    # Unity basics
    needed.add("using UnityEngine;")
    if any(e.using_namespace == "UnityEngine.UI" for e in bindings):
        needed.add("using UnityEngine.UI;")

    return "\n".join(sorted(needed))


def _build_properties(bindings: List[BindingEntry]) -> str:
    """Build property declarations section."""
    if not bindings:
        return "        // (no bindings detected)"

    lines = []
    for entry in bindings:
        short_type = entry.component_type
        lines.append(
            f"        public {short_type} {entry.property_name} {{ get; private set; }}"
        )

    return "\n".join(lines)


def _build_bind_controls(bindings: List[BindingEntry]) -> str:
    """Build BindControls() method body."""
    if not bindings:
        return "            // No controls to bind"

    lines = []
    # Calculate max lengths for alignment
    max_prop = max(len(e.property_name) for e in bindings)

    for entry in bindings:
        short_type = entry.component_type
        prop = entry.property_name
        path = entry.child_path
        # Align assignments
        pad = " " * (max_prop - len(prop))
        lines.append(
            f"            {prop}{pad} = transform.Find(\"{path}\")"
            f"?.GetComponent<{short_type}>();"
        )

    return "\n".join(lines)
