// Auto-generated by UiCodeGenerator on 2026-05-24 01:39:10
// Source prefab: Assets/AssetBundles/UI/MainHudForm/MainHudForm.prefab
// DO NOT EDIT MANUALLY

using GenBall.Utils.CodeGenerator.UI;
using UnityEngine;
using UnityEngine.UI;
using Yueyn.UI;

namespace GenBall.UI
{
    public partial class MainHudFormView : UIBusinessFormBase
    {
        private UiViewBinding _binding;

        // -- Bound Controls --
        public Image ImgAAA { get; private set; }

        // -- Auto-Binding --

        protected override void DoBusinessStart()
        {
            base.DoBusinessStart();
            BindControls();
        }

        private void BindControls()
        {
            _binding = GetComponent<UiViewBinding>();
            ImgAAA = _binding.GetBinding<Image>("ImgAAA");
        }
    }
}
