// Auto-generated by UiCodeGenerator on 2026-05-24 01:39:10
// Source prefab: Assets/AssetBundles/UI/MainHudForm/MainHudForm.prefab
// DO NOT EDIT MANUALLY

using Yueyn.UI;

namespace GenBall.UI
{
    public partial class MainHudFormLogic : BusinessFormLogic
    {
        // -- Form Configuration --

        public override string PrefabPath =>
            "Assets/AssetBundles/UI/MainHudForm/MainHudForm.prefab";

        public override UIFormType FormType => UIFormType.Persistent;

        // -- View Reference --

        public MainHudFormView View { get; private set; }

        // -- Lifecycle --

        public override void OnCreate()
        {
            base.OnCreate();
        }

        protected override void OnFormBound(UIFormScript form)
        {
            base.OnFormBound(form);
            View = form.GetComponentInChildren<MainHudFormView>();
        }

        protected override void OnFormUnbound(UIFormScript form)
        {
            View = null;
            base.OnFormUnbound(form);
        }

        // -- Convenience --

        public static MainHudFormLogic Open()
        {
            return BusinessLogicManager.Instance.CreateFormLogic<MainHudFormLogic>();
        }
    }
}
